In [ ]:
import pandas as pd

In [ ]:
car = pd.read_csv("C:\\Users\\Manooj\\OneDrive\\Desktop\\Pictures\\Documents\\car.csv")
car.head()

,Unnamed: 0,date,open,high,low,close,volume,Unnamed: 7
0,0.0,30-09-2022,75.617410,76.164700,75.252548,75.252548,5079137.0,NaN
1,1.0,03-10-2022,75.252548,75.453222,73.884320,74.614044,2403446.0,NaN
2,2.0,04-10-2022,75.434974,79.795067,74.796470,79.795067,1599630.0,NaN
3,3.0,05-10-2022,79.448447,81.765314,78.919397,80.196411,1321304.0,NaN
4,4.0,06-10-2022,81.820036,85.468644,81.491661,82.750435,2217065.0,NaN

In [ ]:
car.shape

(9, 8)

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5 non-null      float64
 1   date        5 non-null      object
 2   open        5 non-null      float64
 3      high     5 non-null      float64
 4   low         5 non-null      float64
 5   close       5 non-null      float64
 6   volume      5 non-null      float64
 7   Unnamed: 7  0 non-null      float64
dtypes: float64(7), object(1)
memory usage: 708.0+ bytes

In [ ]:
car.describe()

,Unnamed: 0,open,high,low,close,volume,Unnamed: 7
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000e+00,0.0
mean,2.000000,77.514683,79.729389,76.868879,78.521701,2.524116e+06,NaN
std,1.581139,2.971430,4.125559,3.216743,3.473667,1.494858e+06,NaN
min,0.000000,75.252548,75.453222,73.884320,74.614044,1.321304e+06,NaN
25%,1.000000,75.434974,76.164700,74.796470,75.252548,1.599630e+06,NaN
50%,2.000000,75.617410,79.795067,75.252548,79.795067,2.217065e+06,NaN
75%,3.000000,79.448447,81.765314,78.919397,80.196411,2.403446e+06,NaN
max,4.000000,81.820036,85.468644,81.491661,82.750435,5.079137e+06,NaN

In [ ]:
car.info()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (10193982.py, line 2)